# Grasping the essence of NumPy arrays

**Numpy** is written in C and an array is one block of memory with every elements stroed as the same C value, side by side for easier retrevial.

**Numpy arrarys** are a sequence of homogeneous elements, which means they can only hold the same type in one array such an an int,float, double, ect.


There are many ways to make an array: 

1. `np.array()` with data type as an argument `dtype =`
    - **bool:** only uses one byte. basicly a True or False value, and only on 0 does Bool go to false
    
    - **int:** if given a decimal it only take the whole number (always rounds down on pos, and round up on negitive). This is called *Truncation*.
    
    - **float:** floatX
    
    ***OLD C NAMES FOR DATA TYPES***
    
    - **long:** integeer with atleast 32 bits. int32 (will never set a fixed side because the compiler on each operating system will decide the side)
    
    - **double:**  Double Precision, and is a **FLOAT** twice the size of C's 32 bit float, so it's 64 bits
    
    - **long double:** will never set a fixed side because the compiler on each operating system will decide the size.. but long double means a flaot at least as big as a double. 

if you leave the type off, Numpy will choose for the user. 

In [ ]:
import numpy as np
num_list = [1,2,3,4,5,6,7,8,9,10]

# use the array fucntion (it is not a method becuase it does not belong to a class)
arr = np.array(num_list)
print(arr)

# Data Types
print(f"Bool: {np.array([0.00001, 0, -12], dtype = bool)}") # only on 0 does Bool go to false
print(f"int: {np.array([4.0, 2.9, -12.5], dtype = int)}") 
print(f"float: {np.array([12, 7, 30], dtype = float)}")  # just puts a decimal point after (this is likely float64 or float 32)


# this is the C names in which NumPy is written in. 
for t in [np.long, np.double, np.longdouble]:
      arr = np.array([1, 2, 3], dtype=t)
      print(arr.dtype, arr.dtype.itemsize, "bytes")




# Arrange Method. 3 inputs: start, stop (-1), step.  Step is optional, defaults to 1, and so is the second condition.
# similar to range function but returns an array instead of a list.
arange = np.arange(1,11) # or np.arange(11)

print(arange)

#Zero's method. Creates an array (like a matrix) for a given input. Multiple both to get total number count
# note the input is a tuple because the first position is the shape (row, col), and the second is DTYPE 
zeros = np.zeros((3,4)) # 3 rows, 4 columns


print("Array is set with zeros: \n ", zeros)

# Same girl different Number
ones = np.ones((3,4))
print("Array is set with ones: \n", ones)



[ 1  2  3  4  5  6  7  8  9 10]
Bool: [ True False  True]
int: [  4   2 -12]
float: [12.  7. 30.]
int32 4 bytes
float64 8 bytes
float64 8 bytes
[ 1  2  3  4  5  6  7  8  9 10]
Array is set with zeros: 
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array is set with ones: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# page 42
# creates the array with the value specified in the second position

full = np.full((2,3), 5) # should make 2 rows by 3 cols and have 5 in all spaces

print("method in numpy FULL activated: \n", full)

# if col number and row number are the same then 1, else 0
 # can input one number to get the grid, or type a second and you can get col row
 # can be used for one-hot encoding or correlation matrix
eye = np.eye(7)

print(eye)


empty = np.empty((5,4)) # creates an empty array with values stored in the memory location based on the size of the array.
# This is not a good way to create an array because it will have random values in it, but good for seeing what is in memory.  
# It is faster than zeros or ones because it does not have to fill the array with values.
print("Array is set with empty: \n", empty)

# first random is a submodule (smaller moduler) of numpy used to generate random numbers.  
# The random module has many functions to generate random numbers, but the most common is the random function which generates a random number between 0 and 1.
# The shape of the array is specified in the input.  The output is a 2D array with the specified shape.
random = np.random.random((3,4))
print("Array is set with random: \n", random)


method in numpy FULL activated: 
 [[5 5 5]
 [5 5 5]]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
Array is set with empty: 
 [[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
Array is set with random: 
 [[0.79661624 0.58906597 0.14354283 0.68062148]
 [0.26750855 0.60560991 0.66931113 0.67883801]
 [0.4701489  0.36549692 0.63060905 0.55755291]]


In [ ]:

# if you under shoot you get an error, if you over shoot you get an error. the shape of the array has to hold the same amount of values as the new array
array = np.arange(10).reshape(5,2)is 2 hours in 5 pages 

print(array)

# generates an array based on a given array objects dimension with all zeros
arr_zeros = np.zeros_like(array, dtype = bool)

print("Array is set with zeros based on the shape of the array: \n", arr_zeros)


# generates an array based on the array objects dimension with all ones

arr_ones = np.ones_like(array, dtype = float)
print("Array is set with ones based on the shape of the array: \n", arr_ones)

# generates an array based on the array objects dimension with constant values

arr_full = np.full_like(array, np.pi, dtype = np.float32) 
print("Array is set with full based on the shape of the array: \n", arr_full)



[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Array is set with zeros based on the shape of the array: 
 [[False False]
 [False False]
 [False False]
 [False False]
 [False False]]
Array is set with ones based on the shape of the array: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Array is set with full based on the shape of the array: 
 [[3.1415927 3.1415927]
 [3.1415927 3.1415927]
 [3.1415927 3.1415927]
 [3.1415927 3.1415927]
 [3.1415927 3.1415927]]


# Array Properties and Attributes 

Array indexing is similar to a python list, and starts from 0. The Numpy library basicly used a C Api to execute many lower-level numerical operations in compiled C code which makes the process much much faster (10 - 100x in some cases). 

Numpy also executes `vectorized operations` which means a line of code than can work on the entire array all at once. 

EXAMPLE: prices * 1.05

Mind you it is not only faster, but also memory efficent becuase python has to hold a row of addresses (about 8 bytes each) while numpy has them sitting next to each other so it can cache.

When the chip reads one spot in regular memory, it also copies in the bytes nearby. In an array, the next values are already in
the cache before the loop needs them. In a list, each step jumps to a different address, and the processor has to wait while that
object is fetched.

| Approach                         | Memory | Time to multiply by 1.05 |
| -------------------------------- | -----: | -----------------------: |
| Python list with a loop          |  32 MB |                    50 ms |
| NumPy array, `arr * 1.05`        |   8 MB |                   2.7 ms |
| Python loop over the NumPy array |   8 MB |                    96 ms |

<br>
**Note** above that the python loop over the NumPy Array was slower. This is because the C loop + the memory effencity of the array together is what makes this fast.


In [ ]:
arr2 = np.arange(10)

number = 5
#type will find the object type of the variable, and dtype will find the data type of the array.
print(type(arr2))
print(arr2.dtype)


print(arr2.shape)
print(arr2) # 1D looks like a list (its an array through)

<class 'numpy.ndarray'>
int64
(10,)
[0 1 2 3 4 5 6 7 8 9]


# SELECTING ARRAY ELEMENTS


In [ ]:

arr = np.array([[5,6],[7,8]]) # rows [5,6] and columns are each []; 2D array
print(arr)

[[5 6]
 [7 8]]
